const cfg = window.VAPORIX_CONFIG;
if(!cfg?.SUPABASE_URL || !cfg?.SUPABASE_ANON_KEY) throw new Error('config.js не загружен или не настроен.');
const sb = supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);
const $=id=>document.getElementById(id);
let categories=[],products=[],orders=[],refreshTimer=null,draftFlavors=[];
const ORDER_STATUSES=[['new','Создан'],['paid','Оплачен'],['processing','В обработке'],['shipped','Отправлен'],['completed','Завершён'],['cancelled','Отменён']];
const PAYMENT_STATUSES=[['pending','Ожидает оплаты'],['paid','Оплачен'],['failed','Ошибка оплаты'],['refunded','Возврат']];

document.addEventListener('DOMContentLoaded',init);
async function init(){
  $('loginForm')?.addEventListener('submit',login);$('logoutBtn')?.addEventListener('click',logout);$('refreshBtn')?.addEventListener('click',refreshAll);$('addProductBtn')?.addEventListener('click',()=>openProduct());$('addCategoryBtn')?.addEventListener('click',()=>openCategory());$('productForm')?.addEventListener('submit',saveProduct);$('categoryForm')?.addEventListener('submit',saveCategory);$('productSearch')?.addEventListener('input',renderProducts);$('addFlavorBtn')?.addEventListener('click',addFlavor);$('pFlavorInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addFlavor()}});$('pImageFile')?.addEventListener('change',previewProductImage);$('cImageFile')?.addEventListener('change',previewCategoryImage);document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',e=>e.target.closest('dialog')?.close()));document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>showSection(b.dataset.section)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>showSection(b.dataset.go)));
  const {data:{session}}=await sb.auth.getSession();if(session&&await checkAdmin())enterApp(session.user);
}
async function login(e){e.preventDefault();$('loginError').textContent='';const {data,error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error){$('loginError').textContent=error.message;return}if(!(await checkAdmin())){await sb.auth.signOut();$('loginError').textContent='У этого аккаунта нет прав администратора.';return}enterApp(data.user)}
async function checkAdmin(){const {data,error}=await sb.rpc('is_admin');return !error&&data===true}
function enterApp(user){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('userEmail').textContent=user.email||'';loadAll()}
async function logout(){await sb.auth.signOut();location.reload()}
function showSection(id){document.querySelectorAll('.section').forEach(s=>s.classList.add('hidden'));$(id)?.classList.remove('hidden');document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.section===id));$('sectionTitle').textContent={dashboard:'Обзор',products:'Товары',categories:'Категории',orders:'Заказы'}[id]||id;if(id==='products')renderProducts();if(id==='categories')renderCategories();if(id==='orders')renderOrders()}
async function refreshAll(){const button=$('refreshBtn');if(!button)return;clearTimeout(refreshTimer);button.disabled=true;button.textContent='↻ Обновляю…';try{const ok=await loadAll();button.textContent=ok===false?'Ошибка — повторить':'✓ Обновлено';if(ok!==false)refreshTimer=setTimeout(()=>button.textContent='↻ Обновить',2200)}catch(e){button.textContent='Ошибка — повторить';toast(e?.message||'Не удалось обновить данные.')}finally{button.disabled=false}}
async function loadAll(){const [c,p,o]=await Promise.all([sb.from('categories').select('*').order('sort_order').order('name'),sb.from('products').select('*, categories(name)').order('created_at',{ascending:false}),sb.from('orders').select('*').order('created_at',{ascending:false})]);if(c.error){toast(c.error.message);return false}if(p.error){toast(p.error.message);return false}if(o.error){toast(o.error.message);return false}categories=c.data||[];products=p.data||[];orders=o.data||[];window.__vaporixProducts=products;$('statCategories').textContent=categories.length;$('statProducts').textContent=products.length;$('statActive').textContent=products.filter(x=>x.active&&x.is_active!==false).length;$('statOrders').textContent=orders.length;renderProducts();renderCategories();renderOrders();fillCategorySelect();return true}
function productFlavorCount(p){return Array.isArray(p.flavors)?p.flavors.filter(Boolean).length:0}
function renderProducts(){const q=($('productSearch')?.value||'').trim().toLowerCase();const rows=products.filter(p=>`${p.name||''} ${p.slug||''}`.toLowerCase().includes(q));$('productsBody').innerHTML=rows.map(p=>{const fc=productFlavorCount(p);const stock=Number(p.stock||0);return `<tr><td>${p.image_url?`<img class="thumb" src="${esc(p.image_url)}" alt="">`:'—'}</td><td><strong>${esc(p.name)}</strong><br><small class="muted">${esc(p.slug)}</small>${fc?`<br><span class="admin-mini">${fc} вкусов</span>`:''}</td><td>${esc(p.categories?.name||'—')}</td><td>${money(p.price)}</td><td><strong>${stock}</strong>${fc?`<br><small class="muted">по вкусам</small>`:''}</td><td><span class="badge ${p.active&&p.is_active!==false?'ok':'off'}">${p.active&&p.is_active!==false?'Активен':'Скрыт'}</span></td><td><div class="rowActions"><button onclick="openProduct(${p.id})">Изменить</button><button class="dangerBtn" onclick="deleteProduct(${p.id})">Удалить</button></div></td></tr>`}).join('')||'<tr><td colspan="7" class="muted">Товаров нет</td></tr>'}
function renderCategories(){$('categoriesBody').innerHTML=categories.map(c=>`<tr><td>${c.image_url?`<img class="thumb" src="${esc(c.image_url)}" alt="">`:'—'}</td><td><strong>${esc(c.name)}</strong></td><td>${esc(c.slug)}</td><td><div class="rowActions"><button onclick="openCategory(${c.id})">Изменить</button><button class="dangerBtn" onclick="deleteCategory(${c.id})">Удалить</button></div></td></tr>`).join('')||'<tr><td colspan="4" class="muted">Категорий нет</td></tr>'}
function statusOptions(current){return ORDER_STATUSES.map(([v,l])=>`<option value="${v}" ${String(current||'new')===v?'selected':''}>${l}</option>`).join('')}
function paymentOptions(current){return PAYMENT_STATUSES.map(([v,l])=>`<option value="${v}" ${String(current||'pending')===v?'selected':''}>${l}</option>`).join('')}
function renderOrders(){$('ordersBody').innerHTML=orders.map(o=>`<tr><td><strong>${esc(o.order_number||o.order_code||('#'+o.id))}</strong><br><small class="muted">ID ${esc(o.id)}</small></td><td><strong>${esc(o.customer_name||'—')}</strong><br><small class="muted">${esc(o.customer_email||'—')}</small><br><small class="muted">${esc(o.customer_phone||'—')}</small></td><td><strong>${money(o.total)}</strong></td><td><select class="admin-status-select" onchange="setOrderStatus(${o.id},this.value)" aria-label="Статус заказа">${statusOptions(o.status)}</select><select class="admin-status-select admin-payment-select" onchange="setPaymentStatus(${o.id},this.value)" aria-label="Статус оплаты">${paymentOptions(o.payment_status)}</select></td><td>${o.created_at?new Date(o.created_at).toLocaleString('ru-RU'):'—'}</td><td><button class="secondary" onclick="openOrder(${o.id})">Подробнее</button></td></tr>`).join('')||'<tr><td colspan="6" class="muted">Заказов нет</td></tr>'}
async function openOrder(id){const o=orders.find(x=>Number(x.id)===Number(id));if(!o)return;const {data:items,error}=await sb.from('order_items').select('*').eq('order_id',id).order('id');if(error)return toast(error.message);const modal=document.createElement('dialog');modal.className='orderDetailDialog';modal.innerHTML=`<div class="orderDetailModal"><div class="orderDetailHead"><div><h2>Заказ ${esc(o.order_number||o.order_code||('#'+o.id))}</h2><small class="muted">${o.created_at?new Date(o.created_at).toLocaleString('ru-RU'):''}</small></div><button class="icon" type="button">×</button></div><div class="orderDetailGrid"><section><h3>Клиент</h3><p><b>${esc(o.customer_name||'—')}</b></p><p>${esc(o.customer_email||'—')}</p><p>${esc(o.customer_phone||'—')}</p></section><section><h3>Доставка</h3><p>${esc(o.delivery_address||'—')}</p></section></div><section><h3>Товары</h3><div class="adminOrderItems">${(items||[]).map(x=>`<div class="adminOrderItem"><div><b>${esc(x.product_name)}</b>${x.flavor?`<small>Вкус: ${esc(x.flavor)}</small>`:''}</div><span>${esc(x.quantity)} × ${money(x.price)}</span></div>`).join('')||'<p class="muted">Позиции не найдены.</p>'}</div></section><div class="orderDetailTotal"><span>Итого</span><b>${money(o.total)}</b></div><div class="orderDetailActions"><button class="secondary" type="button" data-close-order>Закрыть</button></div></div>`;document.body.appendChild(modal);modal.showModal();modal.querySelector('.icon').onclick=()=>modal.close();modal.querySelector('[data-close-order]').onclick=()=>modal.close();modal.addEventListener('close',()=>modal.remove())}
async function setOrderStatus(id,status){if(!ORDER_STATUSES.some(x=>x[0]===status))return;const {error}=await sb.from('orders').update({status}).eq('id',id);if(error){toast(error.message);await loadAll();return}const o=orders.find(x=>Number(x.id)===Number(id));if(o)o.status=status;renderOrders()}
async function setPaymentStatus(id,payment_status){if(!PAYMENT_STATUSES.some(x=>x[0]===payment_status))return;const {error}=await sb.from('orders').update({payment_status}).eq('id',id);if(error){toast(error.message);await loadAll();return}const o=orders.find(x=>Number(x.id)===Number(id));if(o)o.payment_status=payment_status;renderOrders()}
function fillCategorySelect(){const usable=categories.filter(c=>c.slug!=='all');if($('pCategory'))$('pCategory').innerHTML='<option value="">Без категории</option>'+usable.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}
function renderFlavorEditor(){const list=$('flavorAdminList');if(!list)return;list.innerHTML=draftFlavors.length?draftFlavors.map((f,i)=>`<span class="flavor-admin-pill">${esc(typeof f==='string'?f:f.name)}${typeof f==='object'?` <small>${Number(f.stock||0)} шт.</small>`:''}<button type="button" onclick="removeFlavor(${i})" aria-label="Удалить вкус">×</button></span>`).join(''):'<span class="flavor-admin-empty">Вкусов пока нет. Добавь первый вкус ниже.</span>';if($('flavorAdminStatus'))$('flavorAdminStatus').textContent=`Вкусов: ${draftFlavors.length}`}
function addFlavor(){const input=$('pFlavorInput'),name=input?.value.trim();if(!name)return;if(!draftFlavors.some(x=>String(typeof x==='string'?x:x.name).toLowerCase()===name.toLowerCase()))draftFlavors.push({name,stock:0});input.value='';renderFlavorEditor();input.focus()}
window.removeFlavor=i=>{draftFlavors.splice(Number(i),1);renderFlavorEditor()};
function openProduct(id=null){$('productError').textContent='';$('productForm').reset();fillCategorySelect();$('pImagePreview').style.display='none';$('productId').value=id||'';$('productDialogTitle').textContent=id?'Изменить товар':'Новый товар';draftFlavors=[];if(id){const p=products.find(x=>Number(x.id)===Number(id));if(!p)return;$('pName').value=p.name||'';$('pSlug').value=p.slug||'';$('pCategory').value=p.category_id||'';$('pPrice').value=p.price??'';$('pWholesale').value=p.wholesale_price??'';$('pStock').value=p.stock??0;$('pImage').value=p.image_url||'';$('pDescription').value=p.description||'';$('pActive').checked=p.active!==false;if(p.image_url){$('pImagePreview').src=p.image_url;$('pImagePreview').style.display='block'}setTimeout(()=>window.renderTierRows?.(p.tiers||[]),0)}else setTimeout(()=>window.renderTierRows?.([]),0);renderFlavorEditor();$('productDialog').showModal()}
async function saveProduct(e){e.preventDefault();$('productError').textContent='';const id=$('productId').value;let imageUrl=$('pImage').value.trim()||null;const file=$('pImageFile').files?.[0];if(file){try{imageUrl=await uploadImage(file,'products')}catch(err){$('productError').textContent=err.message||String(err);return}}const tiers=Array.from(document.querySelectorAll('#tierRows .tierRow')).map(row=>({qty:Number(row.querySelector('.tierQty')?.value),price:Number(row.querySelector('.tierPrice')?.value)})).filter(x=>x.qty>0&&Number.isFinite(x.price)).sort((a,b)=>a.qty-b.qty);const payload={name:$('pName').value.trim(),slug:$('pSlug').value.trim(),category_id:$('pCategory').value?Number($('pCategory').value):null,price:Number($('pPrice').value),wholesale_price:$('pWholesale').value?Number($('pWholesale').value):null,stock:Math.max(0,Math.floor(Number($('pStock').value)||0)),image_url:imageUrl,description:$('pDescription').value.trim()||null,active:$('pActive').checked,tiers,flavors:draftFlavors.map(x=>String(typeof x==='string'?x:x.name).trim()).filter(Boolean)};const res=id?await sb.from('products').update(payload).eq('id',Number(id)):await sb.from('products').insert(payload).select('id').single();if(res.error){$('productError').textContent=res.error.message;return}const productId=Number(id||res.data?.id);if(productId){const flavors=draftFlavors.map(x=>({name:String(typeof x==='string'?x:x.name).trim(),stock:Math.max(0,Math.floor(Number(typeof x==='string'?0:x.stock)||0))})).filter(x=>x.name);const fr=await sb.rpc('admin_set_product_flavors',{p_product_id:productId,p_flavors:flavors});if(fr.error){$('productError').textContent=fr.error.message;return}}$('productDialog').close();await loadAll();showSection('products')}
async function deleteProduct(id){if(!confirm('Удалить товар? Это действие нельзя отменить.'))return;const {error}=await sb.from('products').delete().eq('id',id);if(error)return toast(error.message);await loadAll()}
function openCategory(id=null){$('categoryError').textContent='';$('categoryForm').reset();$('categoryId').value=id||'';$('cImagePreview').style.display='none';if(id){const c=categories.find(x=>Number(x.id)===Number(id));if(!c)return;$('cName').value=c.name||'';$('cSlug').value=c.slug||'';$('cImage').value=c.image_url||'';if(c.image_url){$('cImagePreview').src=c.image_url;$('cImagePreview').style.display='block'}}$('categoryDialog').showModal()}
async function saveCategory(e){e.preventDefault();$('categoryError').textContent='';const id=$('categoryId').value;let imageUrl=$('cImage').value.trim()||null;const file=$('cImageFile').files?.[0];if(file){try{imageUrl=await uploadImage(file,'categories')}catch(err){$('categoryError').textContent=err.message||String(err);return}}const payload={name:$('cName').value.trim(),slug:$('cSlug').value.trim(),image_url:imageUrl,is_active:true};const res=id?await sb.from('categories').update(payload).eq('id',Number(id)):await sb.from('categories').insert(payload);if(res.error){$('categoryError').textContent=res.error.message;return}$('categoryDialog').close();await loadAll();showSection('categories')}
async function deleteCategory(id){const c=categories.find(x=>Number(x.id)===Number(id));if(c?.slug==='all')return toast('Категорию «Все товары» удалять нельзя.');if(!confirm('Удалить категорию?'))return;const {error}=await sb.from('categories').delete().eq('id',id);if(error)return toast(error.message);await loadAll()}
function safeFileName(name){return name.toLowerCase().replace(/[^a-z0-9._-]+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'')||'image'}
async function uploadImage(file,folder){if(!file.type.startsWith('image/'))throw new Error('Можно загружать только изображения.');if(file.size>8*1024*1024)throw new Error('Файл слишком большой. Максимум 8 МБ.');const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${folder}/${Date.now()}-${crypto.randomUUID()}.${safeFileName(ext)}`;const {error}=await sb.storage.from('product-images').upload(path,file,{cacheControl:'3600',upsert:false});if(error)throw error;return sb.storage.from('product-images').getPublicUrl(path).data.publicUrl}
function previewProductImage(e){const f=e.target.files?.[0];if(f){$('pImagePreview').src=URL.createObjectURL(f);$('pImagePreview').style.display='block'}}
function previewCategoryImage(e){const f=e.target.files?.[0];if(f){$('cImagePreview').src=URL.createObjectURL(f);$('cImagePreview').style.display='block'}}
function money(v){return `${Number(v||0).toFixed(2)} €`}
function esc(v){return String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]))}
function toast(msg){alert(msg)}
window.openProduct=openProduct;window.openCategory=openCategory;window.setOrderStatus=setOrderStatus;window.setPaymentStatus=setPaymentStatus;window.openOrder=openOrder;
