(function(){
'use strict';
/* VAPORIX mobile input safety layer — V5
   IMPORTANT: a swipe must NEVER become a click. iOS can synthesize a click
   after a touch sequence, so we explicitly cancel clicks that followed motion. */
if(window.__VAPORIX_FIXES_V5)return;
window.__VAPORIX_FIXES_V5=true;

const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const norm=s=>String(s||'').replace(/\s+/g,' ').trim().toLowerCase();

let touchActive=false,touchMoved=false,touchStartX=0,touchStartY=0,touchStartedAt=0,suppressClicksUntil=0;
const MOVE_THRESHOLD=8;
document.addEventListener('touchstart',e=>{if(!e.touches||!e.touches.length)return;const t=e.touches[0];touchActive=true;touchMoved=false;touchStartX=t.clientX;touchStartY=t.clientY;touchStartedAt=Date.now()},{capture:true,passive:true});
document.addEventListener('touchmove',e=>{if(!touchActive||!e.touches||!e.touches.length)return;const t=e.touches[0];if(Math.abs(t.clientX-touchStartX)>MOVE_THRESHOLD||Math.abs(t.clientY-touchStartY)>MOVE_THRESHOLD){touchMoved=true;suppressClicksUntil=Date.now()+700}},{capture:true,passive:true});
document.addEventListener('touchend',()=>{if(touchActive&&touchMoved)suppressClicksUntil=Math.max(suppressClicksUntil,Date.now()+700);touchActive=false},{capture:true,passive:true});
document.addEventListener('touchcancel',()=>{if(touchActive&&touchMoved)suppressClicksUntil=Math.max(suppressClicksUntil,Date.now()+700);touchActive=false;touchMoved=true},{capture:true,passive:true});
document.addEventListener('click',e=>{if(Date.now()<suppressClicksUntil){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation()}},true);

function productsList(){try{if(Array.isArray(window.products))return window.products;if(typeof products!=='undefined'&&Array.isArray(products))return products;if(Array.isArray(window.VAPORIX_PRODUCTS))return window.VAPORIX_PRODUCTS}catch(e){}return []}
function cartList(){try{if(typeof cart!=='undefined'&&Array.isArray(cart))return cart}catch(e){}if(Array.isArray(window.cart))return window.cart;window.cart=[];return window.cart}
function isAddButton(el){if(!el)return false;const t=norm(el.textContent);return t.includes('добавить в корзину')||t.includes('add to cart')||t.includes('додати в кошик')||t.includes('añadir al carrito')||t.includes('in den warenkorb')}
function cardFor(el){return el?.closest?.('[data-id],[data-product-id],.card,article,[class*="product-card"],[class*="productCard"],.product')||null}
function productFor(el){const ps=productsList();const card=cardFor(el);const ids=[el?.getAttribute?.('data-product-id'),el?.getAttribute?.('data-id'),card?.getAttribute?.('data-product-id'),card?.getAttribute?.('data-id')].filter(v=>v!=null&&String(v)!=='');for(const id of ids){const p=ps.find(x=>String(x?.id)===String(id));if(p)return p}const attrs=[el?.getAttribute?.('onclick'),card?.getAttribute?.('onclick'),el?.dataset?.action].filter(Boolean).join(' ');const m=attrs.match(/(?:addWithQty|addToCart|addProduct|addToCartWithQty|cartAdd)\s*\(\s*['"]?([^,'")\s]+)/i);if(m){const key=String(m[1]);const p=ps.find(x=>String(x?.id)===key);if(p)return p;const n=Number(key);if(Number.isInteger(n)&&ps[n])return ps[n]}if(card){const text=norm(card.textContent);let best=null,len=0;for(const p of ps){const n=norm(p?.name);if(n&&text.includes(n)&&n.length>len){best=p;len=n.length}}if(best)return best}return null}
async function loadFlavors(p){if(Array.isArray(p.flavors)&&p.flavors.length)return;if(!p?.id)return;try{const db=window.supabase?.createClient?.(window.VAPORIX_CONFIG?.SUPABASE_URL,window.VAPORIX_CONFIG?.SUPABASE_ANON_KEY);if(!db)return;const {data,error}=await db.from('product_flavors').select('name,stock').eq('product_id',p.id).order('id');if(error||!data)return;p.flavors=[];p.flavorStocks={};data.forEach(row=>{const raw=String(row.name||'').trim();const m=raw.match(/^(.*?)\s*📦\s*(?:80\+|\d+)\s*$/);const name=(m?m[1]:raw).trim();if(name){p.flavors.push(name);p.flavorStocks[name]=Math.max(0,Number(row.stock)||0)}});p.stock=p.flavors.reduce((s,f)=>s+(p.flavorStocks[f]||0),0)}catch(e){console.warn('VAPORIX flavor lookup failed',e)}}
function persist(c){try{localStorage.setItem('vaporixCart',JSON.stringify(c))}catch(e){}try{localStorage.setItem('cart',JSON.stringify(c))}catch(e){}try{window.renderCart?.()}catch(e){}try{window.updateCartCount?.()}catch(e){}try{window.render?.()}catch(e){}}
function addToCart(p,qty,flavor){const c=cartList();const x=c.find(i=>String(i?.id)===String(p.id)&&String(i?.flavor||'')===String(flavor||''));if(x)x.qty=Number(x.qty||0)+qty;else c.push({id:p.id,product:p,qty,flavor:flavor||null});window.cart=c;persist(c)}
async function openFlavorChooser(p){if(!p)return;await loadFlavors(p);const flavors=Array.isArray(p.flavors)?p.flavors.map(String).filter(Boolean):Object.keys(p.flavorStocks||{});if(!flavors.length){addToCart(p,1,null);if(typeof window.showCart==='function')window.showCart();return}let m=$('vaporixFlavorFix');if(!m){m=document.createElement('div');m.id='vaporixFlavorFix';document.body.appendChild(m)}const stocks=p.flavorStocks||{};const stock=f=>Object.prototype.hasOwnProperty.call(stocks,f)?Number(stocks[f]||0):Number(p.stock||0);let selected=null,qty=1;m.innerHTML='<div class="vfx-box"><div class="vfx-head"><div><small>Добавить в корзину</small><h2>'+esc(p.name||'Товар')+'</h2></div><button type="button" class="vfx-close">✕</button></div><div class="vfx-label">Выберите вкус</div><div class="vfx-list">'+flavors.map((f,i)=>'<button type="button" class="vfx-option" data-i="'+i+'" '+(stock(f)<=0?'disabled':'')+'><b>'+esc(f)+'</b><small>'+(stock(f)<=0?'Нет в наличии':'В наличии: '+(stock(f)>=80?'80+':stock(f)))+'</small></button>').join('')+'</div><div class="vfx-label">Количество</div><div class="vfx-qty"><button type="button" data-q="-">−</button><strong id="vfxQty">1</strong><button type="button" data-q="+">+</button></div><button type="button" class="vfx-add" disabled>Добавить в корзину</button></div>';m.classList.add('show');document.documentElement.style.overflow='hidden';document.body.style.overflow='hidden';const close=()=>{m.classList.remove('show');document.documentElement.style.overflow='';document.body.style.overflow=''};m.querySelector('.vfx-close').onclick=close;m.onclick=e=>{if(e.target===m)close()};m.querySelectorAll('.vfx-option').forEach(b=>b.onclick=()=>{m.querySelectorAll('.vfx-option').forEach(x=>x.classList.remove('active'));b.classList.add('active');selected=flavors[Number(b.dataset.i)];qty=1;$('vfxQty').textContent='1';m.querySelector('.vfx-add').disabled=false});m.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{const max=selected?Math.max(1,stock(selected)):999;qty=Math.max(1,Math.min(max,qty+(b.dataset.q==='+'?1:-1)));$('vfxQty').textContent=qty});m.querySelector('.vfx-add').onclick=()=>{if(!selected)return;addToCart(p,Math.min(qty,Math.max(1,stock(selected))),selected);close();if(typeof window.showCart==='function')window.showCart()}}
let lastClick=0;document.addEventListener('click',function(e){if(Date.now()<suppressClicksUntil)return;const b=e.target?.closest?.('button,a,[role="button"]');if(!isAddButton(b))return;const now=Date.now();if(now-lastClick<500)return;const p=productFor(b);if(!p)return;lastClick=now;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openFlavorChooser(p)},true);
function armButtons(){document.querySelectorAll('button,a,[role="button"]').forEach(el=>{if(isAddButton(el)){el.removeAttribute('disabled');el.disabled=false;el.style.pointerEvents='auto';el.setAttribute('aria-disabled','false')}})}
function fixCheckoutScroll(){const m=$('checkoutModal');if(!m)return;m.style.height='100dvh';m.style.maxHeight='100dvh';m.style.overflow='hidden';const b=m.querySelector('.checkout-box');if(b){b.style.height='100dvh';b.style.maxHeight='100dvh';b.style.overflowY='auto';b.style.overflowX='hidden';b.style.webkitOverflowScrolling='touch';b.style.touchAction='pan-y';b.style.paddingBottom='130px'}}
function profileOrders(){const p=$('profile');if(!p)return;let s=$('phOrdersSection');if(!s){s=document.createElement('section');s.id='phOrdersSection';s.innerHTML='<div class="ph-orders-title">Заказы</div><div id="phOrdersList"></div>';const a=p.querySelector('.profile-section-title');p.insertBefore(s,a||p.firstChild)}let a=[];try{a=JSON.parse(localStorage.getItem('puffhubOrdersV1')||'[]')||[]}catch(e){}const title=s.querySelector('.ph-orders-title');if(title)title.innerHTML='Заказы <span class="ph-orders-count">'+a.length+'</span>';const list=$('phOrdersList');if(!list)return;if(!a.length){list.innerHTML='<div class="ph-no-orders">У вас пока нет заказов.<br><small>После оформления заказа он появится здесь.</small></div>';return}list.innerHTML=a.map(o=>'<div class="ph-order-card"><b>Заказ '+esc(o.number||o.id||'')+'</b></div>').join('')}

/* Checkout step 1: explicit escape hatch for customers who changed their mind. */
function ensureCheckoutCancel(){
  const modal=$('checkoutModal');
  const summary=$('checkoutSummary');
  if(!modal||!summary||!modal.classList.contains('show'))return;
  const heading=summary.closest('.checkout-box')?.querySelector('.sheet-head h2');
  const isFirstStep=heading&&norm(heading.textContent)==='контактные данные';
  if(!isFirstStep||summary.querySelector('.ph-cancel-checkout'))return;
  const b=document.createElement('button');
  b.type='button';
  b.className='ph-back ph-cancel-checkout';
  b.textContent='Вернуться к покупкам';
  b.onclick=()=>{try{hideCheckout()}catch(e){}try{showCatalog()}catch(e){}};
  summary.appendChild(b);
}

const style=document.createElement('style');style.textContent=`
.checkout-modal{overflow:hidden!important;height:100dvh!important;max-height:100dvh!important}.checkout-modal .checkout-box{position:absolute!important;inset:0!important;left:50%!important;transform:translateX(-50%)!important;width:min(820px,100%)!important;height:100dvh!important;max-height:100dvh!important;overflow-y:auto!important;overflow-x:hidden!important;-webkit-overflow-scrolling:touch!important;touch-action:pan-y!important;overscroll-behavior:contain!important;padding:0 16px 130px!important}
#vaporixFlavorFix{position:fixed;inset:0;z-index:30000;display:grid;place-items:center;padding:18px;box-sizing:border-box;background:rgba(0,0,0,.74);backdrop-filter:blur(10px);touch-action:none}.vfx-box{width:min(560px,100%);max-height:90dvh;overflow-y:auto;-webkit-overflow-scrolling:touch;box-sizing:border-box;background:#29292b;border:1px solid #4a4a50;border-radius:25px;padding:22px;color:#fff;touch-action:pan-y}.vfx-head{display:flex;justify-content:space-between;gap:12px}.vfx-head small,.vfx-label{color:#999;font-size:13px;font-weight:800}.vfx-head h2{margin:3px 0 0;font-size:23px}.vfx-close{width:40px;height:40px;border-radius:12px;background:#1a1a1c;border:1px solid #3d3d43;color:#fff;font-size:18px}.vfx-label{margin:18px 0 9px}.vfx-list{display:grid;grid-template-columns:1fr 1fr;gap:9px}.vfx-option{min-height:58px;border-radius:15px;border:1px solid #4a4a52;background:#19191b;color:#fff;padding:11px 13px;text-align:left}.vfx-option b,.vfx-option small{display:block}.vfx-option small{margin-top:4px;color:#8cff00;font-size:11px}.vfx-option.active{border-color:#965dff;background:#351579}.vfx-option:disabled{opacity:.4}.vfx-qty{height:54px;display:grid;grid-template-columns:54px 1fr 54px;align-items:center;text-align:center;border:1px solid #4a4a50;border-radius:15px;background:#19191b;overflow:hidden}.vfx-qty button{height:100%;background:transparent;color:#fff;font-size:25px;border:0}.vfx-add{width:100%;height:56px;margin-top:18px;border-radius:16px;background:linear-gradient(100deg,#ff299e,#7c42ff);color:#fff;font-weight:900;font-size:16px;border:0}.vfx-add:disabled{opacity:.45}
#phOrdersSection{display:block!important;margin:18px 0 24px!important;padding:16px!important;border:1.5px solid #7044b8!important;border-radius:22px!important;background:linear-gradient(180deg,rgba(54,25,93,.38),rgba(25,25,29,.82))!important;box-shadow:0 0 0 1px rgba(160,100,255,.08),0 12px 35px rgba(0,0,0,.22)!important}.ph-orders-title{font-size:20px!important;font-weight:900!important;margin:0 0 14px!important;color:#fff!important}.ph-orders-count{display:inline-grid;place-items:center;min-width:30px;height:30px;padding:0 8px;border-radius:999px;background:#3a1777;border:1px solid #7044b8;color:#c6a5ff;font-size:13px}.ph-no-orders{padding:18px 14px;border:1px dashed #5a5963;border-radius:16px;background:#171719;color:#aaa;text-align:center}.ph-order-card{padding:15px;border:1.5px solid #3f3d49!important;border-radius:18px!important;background:#171719!important;margin-bottom:10px}
.ph-cancel-checkout{display:block!important;width:100%!important;min-height:48px!important;margin:10px 0 0!important;padding:13px 18px!important;border-radius:14px!important;background:transparent!important;color:#b58cff!important;border:1px solid #5a3a8f!important;font-weight:850!important;font-size:14px!important;text-align:center!important;box-sizing:border-box!important}
.ph-cancel-checkout:hover{background:#32165f!important;color:#fff!important;border-color:#8c5cff!important}
@media(max-width:520px){.vfx-list{grid-template-columns:1fr}}
`;
document.head.appendChild(style);

const observer=new MutationObserver(()=>{armButtons();ensureCheckoutCancel()});
function run(){armButtons();profileOrders();fixCheckoutScroll();ensureCheckoutCancel();if(!observer.__started){observer.observe(document.body,{childList:true,subtree:true});observer.__started=true}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
window.addEventListener('load',run);setTimeout(run,400);setTimeout(run,1500);setInterval(ensureCheckoutCancel,500);
})();
